services:
  db:
    image: postgres:15.7-alpine
    container_name: my_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: my_app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "3000:3000"

volumes:
  db-data:

networks:
  app-network:
